[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  SUGGESTION_WEBHOOK_URL = "https://your-suggestion-webhook-url"
  ROLL_WEBHOOK_URL = "https://your-roll-webhook-url"
