[build]
  publish = "/"  # Specifies that the root directory should be used
  # Remove `functions` line if not using serverless functions

[build.environment]
  SUGGESTION_WEBHOOK_URL = "https://your-suggestion-webhook-url"
  ROLL_WEBHOOK_URL = "https://your-roll-webhook-url"
