name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment variables
      run: |
        echo "SUGGESTION_WEBHOOK_URL=${{ secrets.SUGGESTION_WEBHOOK_URL }}" >> $GITHUB_ENV
        echo "ROLL_WEBHOOK_URL=${{ secrets.ROLL_WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: Replace placeholders
      run: |
        sed -i "s|{{SUGGESTION_WEBHOOK_URL}}|${{ secrets.SUGGESTION_WEBHOOK_URL }}|g" index.html
        sed -i "s|{{ROLL_WEBHOOK_URL}}|${{ secrets.ROLL_WEBHOOK_URL }}|g" index.html

    - name: Deploy the site
      run: |
        # Example: Deploying to GitHub Pages
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add index.html
        git commit -m "Deploy site with updated secrets"
        git push origin main
